# Generated by Django 4.0.3 on 2022-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_detail_completion_detail_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='completion',
            field=models.BooleanField(),
        ),
    ]
