# Generated by Django 4.0.3 on 2022-08-09 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
