# Generated by Django 4.0.3 on 2022-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_detail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfilePicture',
            field=models.FileField(upload_to='media'),
        ),
    ]
